# Generated by Django 3.2.14 on 2024-07-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20240717_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
