# Generated by Django 3.2.14 on 2024-07-24 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingreview',
            name='product_id',
        ),
        migrations.AddField(
            model_name='ratingreview',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.product'),
        ),
    ]
