# Generated by Django 3.2.14 on 2024-08-14 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20240812_1003'),
        ('accounts', '0029_customerorder_updated_at'),
    ]

    operations = [
    ]
