# Generated by Django 3.2.25 on 2024-08-25 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='admission',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='blance',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='date_update',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='recommended_by',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='referrals',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='requested',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
    ]
