# Generated by Django 3.2.25 on 2024-08-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20240825_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
