# Generated by Django 3.2.14 on 2024-09-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20240907_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('customer', 'customer'), ('seller', 'seller')], default='customer', max_length=13, null=True),
        ),
    ]
