# Generated by Django 3.2.14 on 2024-09-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_auto_20240927_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='landmark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='pincode',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='country',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='district',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='housename',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='mobile',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='place',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
