# Generated by Django 3.2.14 on 2024-10-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_auto_20240928_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryaddress',
            old_name='country',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='district',
        ),
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='place',
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='mobile',
            field=models.CharField(max_length=25),
        ),
    ]
