# Generated by Django 3.2.14 on 2024-10-05 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_deliveryaddress_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='is_default',
        ),
        migrations.AddField(
            model_name='profile',
            name='default_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.deliveryaddress'),
        ),
    ]
