# Generated by Django 3.2.14 on 2024-10-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_auto_20241007_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='payment_type',
            field=models.CharField(choices=[('COD', 'COD'), ('UPI', 'UPI'), ('CREDIT CARD', 'CREDIT CARD'), ('DEBIT CARD', 'DEBIT CARD')], default='COD', max_length=50),
        ),
    ]
