# Generated by Django 3.2.14 on 2024-10-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_auto_20241011_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='status',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('1', 'Ordered'), ('2', 'Shipped'), ('3', 'Delivered')], default='1', max_length=50),
        ),
    ]
