# Generated by Django 3.2.14 on 2024-10-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_temporaryusercontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('0', 'Ordered'), ('1', 'Shipped'), ('2', 'Delivered')], default='1', max_length=50),
        ),
    ]
