# Generated by Django 3.2.14 on 2024-10-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_alter_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_order_quantity_five',
            field=models.IntegerField(default=250),
        ),
        migrations.AddField(
            model_name='product',
            name='min_order_quantity_four',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='product',
            name='min_order_quantity_three',
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name='product',
            name='min_order_quantity_two',
            field=models.IntegerField(default=100),
        ),
    ]
