# Generated by Django 3.2.14 on 2024-11-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_auto_20241031_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session_id',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_status',
            field=models.BooleanField(default=True),
        ),
    ]
