# Generated by Django 3.2.14 on 2024-11-08 12:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_auto_20241108_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryusercontact',
            name='session_id',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='temporaryusercontact',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
