# Generated by Django 3.2.14 on 2024-11-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_auto_20241108_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
