# Generated by Django 3.2.14 on 2024-11-23 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0062_auto_20241119_1059'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='is_canceled',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='payment_type',
            field=models.CharField(choices=[('COD', 'COD'), ('UPI', 'UPI'), ('CREDIT CARD', 'CREDIT CARD'), ('DEBIT CARD', 'DEBIT CARD')], default='COD', max_length=50),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='delivery_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.deliveryaddress'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Ordered'), ('2', 'Shipped'), ('3', 'Delivered')], default='1', max_length=50),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
