# Generated by Django 3.2.14 on 2024-12-07 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20241123_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='heading',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
