# Generated by Django 3.2.14 on 2024-12-19 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_specialoffer_specialofferproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.RemoveField(
            model_name='specialofferproduct',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='specialofferproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='SpecialOffer',
        ),
        migrations.DeleteModel(
            name='SpecialOfferProduct',
        ),
    ]
