# Generated by Django 3.2.14 on 2024-12-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20241226_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_banner',
            field=models.ImageField(blank=True, null=True, upload_to='brands/banners/'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='brands/images/'),
        ),
    ]
