# Generated by Django 3.2.25 on 2024-08-23 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_product_category'),
        ('products', '0068_alter_productsize_name_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='PRDDiscountPrice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='PRDISDeleted',
        ),
        migrations.RemoveField(
            model_name='product',
            name='PRDISSale',
        ),
        migrations.RemoveField(
            model_name='product',
            name='PRDISactive',
        ),
        migrations.RemoveField(
            model_name='product',
            name='PRDPrice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='PRDSKU',
        ),
        migrations.RemoveField(
            model_name='product',
            name='PRDSlug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='PRDWeight',
        ),
        migrations.RemoveField(
            model_name='product',
            name='PRDtags',
        ),
        migrations.RemoveField(
            model_name='product',
            name='additional_image_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='additional_image_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='additional_image_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='additional_image_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='content',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date_update',
        ),
        migrations.RemoveField(
            model_name='product',
            name='digital_file',
        ),
        migrations.RemoveField(
            model_name='product',
            name='feedbak_average',
        ),
        migrations.RemoveField(
            model_name='product',
            name='feedbak_number',
        ),
        migrations.RemoveField(
            model_name='product',
            name='height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pieces',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_maincategory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_minicategor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_subcategory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_supercategory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_vendor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='promotional',
        ),
        migrations.RemoveField(
            model_name='product',
            name='width',
        ),
        migrations.AddField(
            model_name='product',
            name='actual_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='Default Product Name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='product_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
