# Generated by Django 3.2.25 on 2024-08-23 08:51

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0020_auto_20220814_0432'),
        ('accounts', '0033_alter_product_category'),
        ('products', '0069_auto_20240823_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='actual_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='offer_percent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='PRDDiscountPrice',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDISDeleted',
            field=models.BooleanField(default=False, verbose_name='Product Deleted'),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDISSale',
            field=models.BooleanField(default=False, verbose_name='Sale'),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDISactive',
            field=models.BooleanField(blank=True, choices=[(True, True), (False, False)], default=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDPrice',
            field=models.FloatField(blank=True, null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDSKU',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SKU'),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDSlug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=150, null=True, unique=True, verbose_name='Slugfiy'),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDWeight',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='SET WEIGHT_KG'),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDtags',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='product',
            name='additional_image_1',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='products/imgs/product_imgs/', verbose_name='Additional  Image_1'),
        ),
        migrations.AddField(
            model_name='product',
            name='additional_image_2',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='products/imgs/product_imgs/', verbose_name='Additional  Image_2'),
        ),
        migrations.AddField(
            model_name='product',
            name='additional_image_3',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='products/imgs/product_imgs/', verbose_name='Additional  Image_3'),
        ),
        migrations.AddField(
            model_name='product',
            name='additional_image_4',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='products/imgs/product_imgs/', verbose_name='Additional  Image_4'),
        ),
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='available'),
        ),
        migrations.AddField(
            model_name='product',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Full Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='digital_file',
            field=models.FileField(blank=True, help_text='Please use our recommended allowed extension are zip , rar', null=True, upload_to='products/files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'rar'])], verbose_name='Digital File'),
        ),
        migrations.AddField(
            model_name='product',
            name='feedbak_average',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Feedbak average'),
        ),
        migrations.AddField(
            model_name='product',
            name='feedbak_number',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Feedbak number'),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='product',
            name='pieces',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='pieces/set'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='products/product.jpg', max_length=500, upload_to='products/imgs/', verbose_name='Product Image'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_maincategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.maincategory', verbose_name='Main Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_minicategor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.minicategory', verbose_name='Mini Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='related_products', to='accounts.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.subcategory', verbose_name='Sub Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_supercategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.supercategory', verbose_name='Super Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='Product Vendor'),
        ),
        migrations.AddField(
            model_name='product',
            name='promotional',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Hot', 'Hot')], default='New', max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.FloatField(blank=True, null=True, verbose_name='Width'),
        ),
    ]
