# Generated by Django 3.2.25 on 2024-08-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0070_auto_20240823_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
    ]
