# Generated by Django 3.2.25 on 2024-08-26 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0072_auto_20240826_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_new_arrival',
        ),
    ]
