# Generated by Django 3.2.14 on 2024-08-29 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0073_auto_20240826_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_vendor',
        ),
    ]
